import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-4 bg-slate-200">
          <nav className="flex justify-between text-xl">
            <Link href="/">Home</Link>
            <span>12</span>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
