import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import CountProvider from "./CountProvider";
import "./globals.css";
import CountLabel from "./ui/CountLabel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Hämta in providern som går vidare till CountButton */}
        <CountProvider>
          <header className="p-4 bg-slate-200">
            <nav className="flex justify-between text-xl">
              <Link href="/">Home</Link>
              <CountLabel />
            </nav>
          </header>
          {children}
        </CountProvider>
      </body>
    </html>
  );
}
