### Startsidan
GET http://localhost:3000

### Sida som inte finns
GET http://localhost:3000/jagfinnsinte


### Hämta produkter
GET http://localhost:3000/products

### Spara en ny produkt
POST http://localhost:3000/products
Content-Type: application/json

{
"title": "Test",
"price": 15
}