### GET ALL
GET http://localhost:3500/api/todos

### GET ONE TODO
GET http://localhost:3500/api/todos/1

### CREATE TODO
POST http://localhost:3500/api/todos
Content-Type: application/application/json

{
    "title": "Äta mat",
    "details": "lorem lorem lorem",
}


### UPDATE TODO
PUT http://localhost:3500/api/todos/1
Content-Type: application/application/json

{
    "title": "Äta mat",
    "details": "lorem lorem lorem",
}

### DELETE ONE TODO
DELETE http://localhost:3500/api/todos/1