### GET ALL BOOKS
GET http://localhost:4400/api/books

### CREATE  A BOOK
POST http://localhost:4400/api/books
Content-Type: application/json

{
    "titlle": "Mysans äventyr på månen",
    "autor": "6628fe26fe7408e6be2482dd",
    "isbn": "E322345566464",
    "publishedDate": "2024-04-11T11:13:04.123Z"
}

### GET ALL AUTHORS
GET http://localhost:4400/api/authors

### CREATE  A AUTHORS
POST http://localhost:4400/api/authors
Content-Type: application/json

{
    "name": "Mysan Mysansson",
    "yearOfBirth": 2013
}